// DEFINE FUNCTION DECLARATION OF A CUSTOM REUSABLE APPLICATION COMPONENT WITH OBJECT PARAMETER OF ACCEPTED PROPS DATA TO ACCESS/USE HERES
function Title({ title, subTitle }) {
  return (
    <div className="section-title">
      <h2>
        {/* TARGET PARAMETERS OF ACCEPTED PROPS DATA TO ACCESS/USE/SHOW ITS VALUE HERE */}
        {title} <span>{subTitle}</span>
      </h2>
    </div>
  );
}


// EXPORT BY DEFAULT THE FUNCTION DECLARATION STATEMENT OBJECT OF THE CUSTOM REUSABLE APPLICATION COMPONENT TO ACCESS/USE IT FROM OUTSIDE OF THIS SEPARATE MODULE JSX FILE
export default Title;
