// SETUP REFERENCE TO THE BUILT-IN OBJECT FROM INSTALLED PACKAGE TO ACCESS/USE IT HERE
import React from "react";
// SETUP REFERENCE TO THE BUILT-IN OBJECT FROM INSTALLED PACKAGE TO ACCESS/USE IT HERE TO SETUP REFERENCE TO THE HTML ELEMENT UNDER A CERTAIN NAME TO ATTACH A CONTENT DATA
import ReactDOM from "react-dom/client";
// SETUP REFERENCE TO THE MAIN CUSTOM REUSABLE APPLICATION COMPONENT TO ACCESS/USE IT HERE
import App from "./App.jsx";
// SETUP REFERENCE TO THE STATIC CSS FILE TO APPLY CSS PROPERTIES TO THE ENTIRE APPLICATION
import "./index.css";

// LETS ATTACH CONTENT DATA OF THE IMPORTED FUNCTION DECLARATION OF THE CUSTOM COMPONENT TO THE HTML ELEMENT TO DISPLAY IT ON SCREEN

// TARGET IMPORTED BUILT-IN OBJECT TO ACCESS '.' TO THE BUILT-IN METHO 'createRoot()' WITH ARGUMENT OF SELECTED HTML ELEMENT UNDER A CERTAIN ID NAME TO ACCESS '.' TO THE BUILT-IN METHOD 'render()' WITH ARGUMENT OF IMPORTED MAIN CUSTOM COMPONENT
ReactDOM.createRoot(document.getElementById("root")).render(
  // TARGET IMPORTED BUILT-IN OBJECT TO ACCESS TO BUILT-IN PROPERTY 'StrictMode' TO RENDER IT WITH <></> HTML TAGS OPERATOR TO MAKE IT AS HTML ELEMENT CONTAINER
  <React.StrictMode>
    {/* TARGET IMPORTED FUNCTION DECLARATION OBJECT TO RENDER IT WITH <></> HTML TAGS OPERATOR TO MAKE IT AS HTML ELEMENT TO ATTACH ITS CONTENT TO THE SELECTED HTML ELEMENT WITH ID 'root' */}
    <App />
  </React.StrictMode>
);
